theme = "kanagawa"
# curzon: good, but meh string literals. wish type anns were grey. bad white funcs
# dark plus: good, but a lot like vs code
# kanagawa: good overall, but not super pretty
# want: different type ann colour, diff gw colour, distinct colours, greyed out comments,
# good string literal colours, visible `.`, greyed out spaces
# zed onedark: good, but bad gw. at least a little different though.
# molokai: doesn't change type ann colour
# tokyonight; ayu*: don't change gw colour
# amberwood: too similar
# heisenberg: neon green :skull:

[editor]
line-number = "relative"
mouse = false
middle-click-paste = false
cursorline = true
# cursorcolumn = true # maybe not?
auto-completion = true
auto-format = true
# true-color = true # test this
# undercurl = true # seems to work fine without this
auto-save = true
color-modes = true
auto-info = true
rulers = [81]
default-line-ending = "lf"
insert-final-newline = true
bufferline = "always"
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "error"

[editor.statusline]
left = [
    "mode", 
    "spinner", 
    "file-name", 
    "read-only-indicator", 
    "file-modification-indicator"
]
center = []
right = [
    "diagnostics", 
    "selections", 
    "register", 
    "position",
    "total-line-numbers",
    "version-control",
    "file-encoding", 
    "file-line-ending",
    "file-type",
]

[editor.lsp]
enable = true
display-messages = true # see how annoying this is
auto-signature-help = true
display-inlay-hints = true
display-signature-help-docs = true
snippets = true
goto-reference-include-declaration = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
"'" = "'"
'"' = '"'
'`' = '`'

[editor.search]
smart-case = true # disable once I learn regex probably
wrap-around = true

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"
nbsp = "all"

[editor.indent-guides]
render = true
# skip-levels # ???

[editor.gutters]
layout = ["diagnostics", "line-numbers", "diff"]

[editor.soft-wrap]
enable = false

[editor.smart-tab]
enable = true
supersede-menu = false

[keys.insert]
# unmap the arrow keys so you're forced to use more vi-like stuff
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"

# vscode-esque entering keybindings
# TODO: find better solution
"C-ret" = "open_below"
"C-S-ret" = "open_above"
