[[language]]
name = "rust"
auto-format = true

roots = [
  "Cargo.toml",
  "Cargo.lock"
]

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'

# [language-server.rust-analyzer.config]
# # command = "rust-analyzer"

[language-server.rust-analyzer.config]
check.command = "clippy"
# cargo.features = "all"

# inlayHints.bindingModeHints.enable = false
# inlayHints.closingBraceHints.minLines = 10
# inlayHints.closureReturnTypeHints.enable = "with_block"
# inlayHints.discriminantHints.enable = "fieldless"
# inlayHints.lifetimeElisionHints.enable = "skip_trivial"
# inlayHints.typeHints.hideClosureInitialization = false

# [language-server.rust-alalyzer.config.check]
# command = "clippy"

[[language]]
name = "html"
roots = [".git"]
language-servers = ["emmet-lsp"]

[language-server.emmet-lsp]
command = "emmet-language-server"
args = ["--stdio"]

# w
# [[language]]
# name = "picasso"
